import React, {useState} from 'react'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import socials from '../socials';
import { Grid, GridItem } from '@chakra-ui/react'






function TenTwelve() {
const [showLinks, setShowLinks] = useState(false)

const firstClick = () => {
    setShowLinks(!showLinks);
}



return (
<Grid templateColumns='repeat(3, 1fr)' gap={6}>
<GridItem w='100%' h='10' > 1. </GridItem> <GridItem id='songLinks' w='100%' h='10'> {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>} </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span onClick={firstClick} style={{cursor: "pointer"}}>intro</span> </GridItem>
<GridItem w='100%' h='10' > 2. </GridItem> <GridItem id='songLinks' w='100%' h='10'> {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>L.ove</span> </GridItem>
<GridItem w='100%' h='10' > 3. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>} </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>I.nterlude</span> </GridItem>
<GridItem w='100%' h='10' > 4. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>} </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>B.</span> </GridItem>
<GridItem w='100%' h='10' > 5. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>R.age</span> </GridItem>
<GridItem w='100%' h='10' > 6. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>A. partofme</span> </GridItem>
<GridItem w='100%' h='10' > 7. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>prelude</span> </GridItem>
<GridItem w='100%' h='10' > 8. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>SUN</span> </GridItem>
<GridItem w='100%' h='10' > 9. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>moon</span> </GridItem>
<GridItem w='100%' h='10' > 10. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>rising.Rising.RISING</span> </GridItem>
<GridItem w='100%' h='10' > 11. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>outro</span> </GridItem>
<GridItem w='100%' h='10' > 12. </GridItem> <GridItem id='songLinks' w='100%' h='10'>  {showLinks && <><a id="spotify" href={socials[6].url}><FontAwesomeIcon icon={socials[5].icon} size="2x"/></a><a id='apple' href={socials[8].url}><FontAwesomeIcon icon={socials[7].icon} size="2x"/></a><a id='amazon' href={socials[9].url}><FontAwesomeIcon icon={socials[9].icon} size="2x"/></a><a id='soundcloud' href={socials[10].url}><FontAwesomeIcon icon={socials[10].icon} size="2x"/></a></>}  </GridItem> <GridItem id='songTitles' w='100%' h='10'> <span style={{cursor: "pointer"}}>Stubborn (bonus)</span> </GridItem>
</Grid>
    )
}
export default TenTwelve;